version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=it4409
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=it4409
    volumes:
      - ./data-docker-ignored:/var/lib/mysql
